from datetime import date
from sqlalchemy import String, Boolean, Date, Numeric, Text
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base, TimestampMixin, SoftDeleteMixin

class VendorMaster(TimestampMixin, SoftDeleteMixin, Base):
    __tablename__ = "vendor_master"

    vendor_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    vendor_name: Mapped[str] = mapped_column(String, index=True, nullable=False)
    legal_name: Mapped[str | None] = mapped_column(String, nullable=True)
    entity_type: Mapped[str | None] = mapped_column(String, nullable=True)
    category: Mapped[str | None] = mapped_column(String, nullable=True)
    sub_category: Mapped[str | None] = mapped_column(String, nullable=True)
    industry: Mapped[str | None] = mapped_column(String, nullable=True)
    gst_number: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    pan_number: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    cin_number: Mapped[str | None] = mapped_column(String, nullable=True)
    contact_person: Mapped[str | None] = mapped_column(String, nullable=True)
    email: Mapped[str | None] = mapped_column(String, nullable=True)
    mobile_number: Mapped[str | None] = mapped_column(String, nullable=True)
    address: Mapped[str | None] = mapped_column(Text, nullable=True)
    city: Mapped[str | None] = mapped_column(String, nullable=True)
    state: Mapped[str | None] = mapped_column(String, nullable=True)
    country: Mapped[str | None] = mapped_column(String, nullable=True)
    pincode: Mapped[str | None] = mapped_column(String, nullable=True)
    contract_id: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    project_name: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    contract_type: Mapped[str | None] = mapped_column(String, nullable=True)
    contract_start_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    contract_end_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    renewal_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    contract_value: Mapped[float | None] = mapped_column(Numeric(15, 2), nullable=True)
    currency: Mapped[str | None] = mapped_column(String, nullable=True)
    base_cost: Mapped[float | None] = mapped_column(Numeric(15, 2), nullable=True)
    support_cost: Mapped[float | None] = mapped_column(Numeric(15, 2), nullable=True)
    maintenance_cost: Mapped[float | None] = mapped_column(Numeric(15, 2), nullable=True)
    hosting_cost: Mapped[float | None] = mapped_column(Numeric(15, 2), nullable=True)
    cloud_cost: Mapped[float | None] = mapped_column(Numeric(15, 2), nullable=True)
    miscellaneous_cost: Mapped[float | None] = mapped_column(Numeric(15, 2), nullable=True)
    tax_percentage: Mapped[float | None] = mapped_column(Numeric(5, 2), nullable=True)
    discount: Mapped[float | None] = mapped_column(Numeric(15, 2), nullable=True)
    payment_flow: Mapped[str | None] = mapped_column(String, nullable=True)
    expected_billing: Mapped[float | None] = mapped_column(Numeric(15, 2), nullable=True)
    payment_type: Mapped[str | None] = mapped_column(String, nullable=True)
    frequency: Mapped[str | None] = mapped_column(String, nullable=True)
    recurring: Mapped[bool | None] = mapped_column(Boolean, index=True, nullable=True)
    bank_name: Mapped[str | None] = mapped_column(String, nullable=True)
    account_holder_name: Mapped[str | None] = mapped_column(String, nullable=True)
    account_number: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    ifsc_code: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    branch_name: Mapped[str | None] = mapped_column(String, nullable=True)
    primary_account: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    status: Mapped[str | None] = mapped_column(String, index=True, nullable=True)
    remarks: Mapped[str | None] = mapped_column(Text, nullable=True)
