"""documents_tab_migration

Revision ID: 3596053d370f
Revises: cc14e2333eca
Create Date: 2026-08-21 12:23:35.214736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3596053d370f'
down_revision: Union[str, Sequence[str], None] = 'cc14e2333eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_audit_log_document_id'), 'document_audit_log', ['document_id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['general_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_business_id'), 'packages', ['business_id'], unique=False)
    op.create_table('package_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['business_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_documents_document_id'), 'package_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_package_documents_package_id'), 'package_documents', ['package_id'], unique=False)
    op.drop_constraint(op.f('accounts_document_id_key'), 'accounts', type_='unique')
    op.drop_constraint(op.f('accounts_person_id_fkey'), 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'person_id')
    op.add_column('business_documents', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'business_documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('documents_person_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_account_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_uploaded_by_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'account_id')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'person_id')
    op.drop_index(op.f('ix_general_info_person_id'), table_name='general_info')
    op.drop_constraint(op.f('general_info_person_id_fkey'), 'general_info', type_='foreignkey')
    op.drop_column('general_info', 'person_id')
    op.drop_constraint(op.f('users_person_id_key'), 'users', type_='unique')
    op.drop_column('users', 'person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_person_id_key'), 'users', ['person_id'], postgresql_nulls_not_distinct=False)
    op.add_column('general_info', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('general_info_person_id_fkey'), 'general_info', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_general_info_person_id'), 'general_info', ['person_id'], unique=False)
    op.add_column('documents', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.VARCHAR(length=50), server_default=sa.text("'BANK_STATEMENT'::character varying"), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_uploaded_by_fkey'), 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('documents_account_id_fkey'), 'documents', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('documents_person_id_fkey'), 'documents', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'business_documents', type_='foreignkey')
    op.drop_column('business_documents', 'uploaded_by')
    op.add_column('accounts', sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('accounts_person_id_fkey'), 'accounts', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('accounts_document_id_key'), 'accounts', ['document_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_package_documents_package_id'), table_name='package_documents')
    op.drop_index(op.f('ix_package_documents_document_id'), table_name='package_documents')
    op.drop_table('package_documents')
    op.drop_index(op.f('ix_packages_business_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_document_audit_log_document_id'), table_name='document_audit_log')
    op.drop_table('document_audit_log')
    # ### end Alembic commands ###
