"""Remove unique constraints from employee_id and vendor_id

Revision ID: 6177a233c1b6
Revises: a61f61f67ad7
Create Date: 2026-08-31 03:11:31.527774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6177a233c1b6'
down_revision: Union[str, Sequence[str], None] = 'a61f61f67ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_master_employee_id'), table_name='employee_master')
    op.create_index(op.f('ix_employee_master_employee_id'), 'employee_master', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_vendor_master_vendor_id'), table_name='vendor_master')
    op.create_index(op.f('ix_vendor_master_vendor_id'), 'vendor_master', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_master_vendor_id'), table_name='vendor_master')
    op.create_index(op.f('ix_vendor_master_vendor_id'), 'vendor_master', ['vendor_id'], unique=True)
    op.drop_index(op.f('ix_employee_master_employee_id'), table_name='employee_master')
    op.create_index(op.f('ix_employee_master_employee_id'), 'employee_master', ['employee_id'], unique=True)
    # ### end Alembic commands ###
