"""spotlite_schema_v2

Revision ID: 905637f89e5d
Revises: 3596053d370f
Create Date: 2026-08-25 14:01:53.517270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '905637f89e5d'
down_revision: Union[str, Sequence[str], None] = '3596053d370f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statement_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('statement_period', sa.String(length=100), nullable=True),
    sa.Column('statement_month', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.add_column('accounts', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('accounts', sa.Column('branch_name', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('accounts', 'account_holder_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('accounts', 'account_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=False)
    op.create_unique_constraint('uq_account_business_number_bank', 'accounts', ['business_id', 'account_number', 'bank_name'])
    op.drop_constraint(op.f('accounts_document_id_fkey'), 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'opening_balance')
    op.drop_column('accounts', 'document_id')
    op.drop_column('accounts', 'statement_month')
    op.drop_column('accounts', 'branch')
    op.drop_column('accounts', 'closing_balance')
    op.drop_column('accounts', 'statement_period')
    op.add_column('category_rules', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.execute('ALTER TABLE category_rules DROP CONSTRAINT IF EXISTS category_rules_pkey CASCADE')
    op.drop_column('category_rules', 'id')
    op.add_column('category_rules', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_primary_key('pk_category_rules', 'category_rules', ['id'])
    op.alter_column('category_rules', 'match_pattern',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('category_rules', 'confidence_score',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    op.add_column('documents', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'documents', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.add_column('intelligence_groups', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('intelligence_groups', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('intelligence_groups', 'group_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'intelligence_groups', ['group_name'])
    op.add_column('merchants', sa.Column('business_id', sa.UUID(), nullable=True))
    op.add_column('merchants', sa.Column('canonical_name', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('subcategory', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=False)
    op.create_foreign_key(None, 'merchants', 'general_info', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('risk_detection_transactions', 'evidence_weight',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('risk_detections', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('risk_detections', 'severity',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('risk_detections', 'risk_score',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('risk_detections', 'confidence_score',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('risk_rules', 'rule_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('risk_rules', 'risk_category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('risk_rules', 'severity',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('risk_rules', 'rule_definition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('risk_rules', 'threshold_value',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_risk_rules_rule_code'), table_name='risk_rules')
    op.create_index(op.f('ix_risk_rules_rule_code'), 'risk_rules', ['rule_code'], unique=True)
    op.add_column('transaction_categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('transaction_categories', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('transaction_categories', 'intelligence_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_categories', 'category_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('transaction_categories_intelligence_group_id_fkey'), 'transaction_categories', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_categories', 'intelligence_groups', ['intelligence_group_id'], ['id'], ondelete='CASCADE')
    op.add_column('transactions', sa.Column('business_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('raw_category', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'general_info', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'transaction_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'raw_category')
    op.drop_column('transactions', 'category_id')
    op.drop_column('transactions', 'business_id')
    op.drop_constraint(None, 'transaction_categories', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_categories_intelligence_group_id_fkey'), 'transaction_categories', 'intelligence_groups', ['intelligence_group_id'], ['id'], ondelete='SET NULL')
    op.alter_column('transaction_categories', 'category_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('transaction_categories', 'intelligence_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transaction_categories', 'updated_at')
    op.drop_column('transaction_categories', 'created_at')
    op.drop_index(op.f('ix_risk_rules_rule_code'), table_name='risk_rules')
    op.create_index(op.f('ix_risk_rules_rule_code'), 'risk_rules', ['rule_code'], unique=False)
    op.alter_column('risk_rules', 'threshold_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    op.alter_column('risk_rules', 'rule_definition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('risk_rules', 'severity',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('risk_rules', 'risk_category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('risk_rules', 'rule_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('risk_detections', 'confidence_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('risk_detections', 'risk_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('risk_detections', 'severity',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('risk_detections', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('risk_detection_transactions', 'evidence_weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.drop_index(op.f('ix_merchants_name'), table_name='merchants')
    op.create_index(op.f('ix_merchants_name'), 'merchants', ['name'], unique=True)
    op.drop_column('merchants', 'updated_at')
    op.drop_column('merchants', 'country')
    op.drop_column('merchants', 'state')
    op.drop_column('merchants', 'city')
    op.drop_column('merchants', 'subcategory')
    op.drop_column('merchants', 'category')
    op.drop_column('merchants', 'canonical_name')
    op.drop_column('merchants', 'business_id')
    op.drop_constraint(None, 'intelligence_groups', type_='unique')
    op.alter_column('intelligence_groups', 'group_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('intelligence_groups', 'updated_at')
    op.drop_column('intelligence_groups', 'created_at')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'account_id')
    op.alter_column('category_rules', 'confidence_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('category_rules', 'match_pattern',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.execute('ALTER TABLE category_rules DROP CONSTRAINT IF EXISTS pk_category_rules CASCADE')
    op.drop_column('category_rules', 'id')
    op.add_column('category_rules', sa.Column('id', sa.UUID(), nullable=False))
    op.create_primary_key('category_rules_pkey', 'category_rules', ['id'])
    op.drop_column('category_rules', 'created_at')
    op.add_column('accounts', sa.Column('statement_period', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('closing_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('accounts', sa.Column('branch', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('statement_month', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('accounts', sa.Column('opening_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('accounts_document_id_fkey'), 'accounts', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_account_business_number_bank', 'accounts', type_='unique')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.alter_column('accounts', 'account_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('accounts', 'account_holder_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'status')
    op.drop_column('accounts', 'branch_name')
    op.drop_column('accounts', 'currency')
    op.drop_table('bank_statement_data')
    # ### end Alembic commands ###
