"""Refactor client to vendor master

Revision ID: a61f61f67ad7
Revises: c2822496dcbc
Create Date: 2026-08-04 11:26:03.654116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a61f61f67ad7'
down_revision: Union[str, Sequence[str], None] = 'c2822496dcbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_master',
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('cin_number', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('base_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('support_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('maintenance_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('hosting_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cloud_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('miscellaneous_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_flow', sa.String(), nullable=True),
    sa.Column('expected_billing', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_holder_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('ifsc_code', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('primary_account', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_master_account_number'), 'vendor_master', ['account_number'], unique=False)
    op.create_index(op.f('ix_vendor_master_contract_id'), 'vendor_master', ['contract_id'], unique=False)
    op.create_index(op.f('ix_vendor_master_gst_number'), 'vendor_master', ['gst_number'], unique=False)
    op.create_index(op.f('ix_vendor_master_id'), 'vendor_master', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_master_ifsc_code'), 'vendor_master', ['ifsc_code'], unique=False)
    op.create_index(op.f('ix_vendor_master_is_deleted'), 'vendor_master', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_vendor_master_pan_number'), 'vendor_master', ['pan_number'], unique=False)
    op.create_index(op.f('ix_vendor_master_project_name'), 'vendor_master', ['project_name'], unique=False)
    op.create_index(op.f('ix_vendor_master_recurring'), 'vendor_master', ['recurring'], unique=False)
    op.create_index(op.f('ix_vendor_master_status'), 'vendor_master', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_master_vendor_id'), 'vendor_master', ['vendor_id'], unique=True)
    op.create_index(op.f('ix_vendor_master_vendor_name'), 'vendor_master', ['vendor_name'], unique=False)
    op.drop_index(op.f('ix_client_master_client_id'), table_name='client_master')
    op.drop_index(op.f('ix_client_master_email'), table_name='client_master')
    op.drop_index(op.f('ix_client_master_id'), table_name='client_master')
    op.drop_index(op.f('ix_client_master_is_deleted'), table_name='client_master')
    op.drop_table('client_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_master',
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('legal_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gst_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pan_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cin_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pincode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_start_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_end_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('renewal_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('base_cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('support_cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maintenance_cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hosting_cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cloud_cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('miscellaneous_cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tax_percentage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_flow', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expected_billing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recurring', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_holder_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ifsc_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('branch_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primary_account', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('client_master_pkey'))
    )
    op.create_index(op.f('ix_client_master_is_deleted'), 'client_master', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_client_master_id'), 'client_master', ['id'], unique=False)
    op.create_index(op.f('ix_client_master_email'), 'client_master', ['email'], unique=False)
    op.create_index(op.f('ix_client_master_client_id'), 'client_master', ['client_id'], unique=True)
    op.drop_index(op.f('ix_vendor_master_vendor_name'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_vendor_id'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_status'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_recurring'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_project_name'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_pan_number'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_is_deleted'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_ifsc_code'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_id'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_gst_number'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_contract_id'), table_name='vendor_master')
    op.drop_index(op.f('ix_vendor_master_account_number'), table_name='vendor_master')
    op.drop_table('vendor_master')
    # ### end Alembic commands ###
