"""Initial schema

Revision ID: c2822496dcbc
Revises: 
Create Date: 2026-08-03 07:18:05.713581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2822496dcbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_master', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('client_master', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('client_master', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('client_master', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('client_master', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('client_master', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_client_master_client_id'), table_name='client_master')
    op.create_index(op.f('ix_client_master_client_id'), 'client_master', ['client_id'], unique=True)
    op.add_column('employee_master', sa.Column('hike_percentage', sa.String(), nullable=True))
    op.add_column('employee_master', sa.Column('pan', sa.String(), nullable=True))
    op.add_column('employee_master', sa.Column('aadhaar', sa.String(), nullable=True))
    op.add_column('employee_master', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('employee_master', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('employee_master', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_master', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('employee_master', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('employee_master', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_employee_master_employee_id'), table_name='employee_master')
    op.create_index(op.f('ix_employee_master_employee_id'), 'employee_master', ['employee_id'], unique=True)
    op.drop_column('employee_master', 'bank_verification_status')
    op.drop_column('employee_master', 'postal_code')
    op.drop_column('employee_master', 'bank_city')
    op.drop_column('employee_master', 'client_allocation')
    op.drop_column('employee_master', 'branch_name')
    op.drop_column('employee_master', 'esic_number')
    op.drop_column('employee_master', 'gross_salary')
    op.drop_column('employee_master', 'salary_cycle')
    op.drop_column('employee_master', 'pan_number')
    op.drop_column('employee_master', 'employee_category')
    op.drop_column('employee_master', 'kyc_status')
    op.drop_column('employee_master', 'net_salary')
    op.drop_column('employee_master', 'aadhaar_number')
    op.drop_column('employee_master', 'salary_account_verified')
    op.drop_column('employee_master', 'salary_transfer_type')
    op.drop_column('employee_master', 'salary_credit_ifsc')
    op.drop_column('employee_master', 'emergency_contact_relation')
    op.drop_column('employee_master', 'ctc')
    op.drop_column('employee_master', 'emergency_contact_name')
    op.drop_column('employee_master', 'vendor_id')
    op.drop_column('employee_master', 'project_allocation')
    op.drop_column('employee_master', 'salary_credit_bank')
    op.drop_column('employee_master', 'payroll_id')
    op.drop_column('employee_master', 'location')
    op.drop_column('employee_master', 'salary_credit_account_number')
    op.drop_column('employee_master', 'upi_id')
    op.drop_column('employee_master', 'salary_hike_percent')
    op.drop_column('employee_master', 'pf_number')
    op.drop_column('employee_master', 'emergency_contact_number')
    op.drop_column('employee_master', 'bank_state')
    op.drop_column('employee_master', 'cost_center')
    op.drop_column('employee_master', 'pan_linked_account')
    op.drop_column('employee_master', 'secondary_bank_flag')
    op.drop_column('employee_master', 'primary_bank_flag')
    op.drop_column('employee_master', 'uan_number')
    op.drop_column('employee_master', 'salary_payment_date')
    op.drop_column('employee_master', 'swift_code')
    op.drop_column('employee_master', 'bank_country')
    op.drop_column('employee_master', 'micr_code')
    op.drop_column('employee_master', 'salary_account')
    op.add_column('import_logs', sa.Column('upload_history_id', sa.UUID(), nullable=False))
    op.add_column('import_logs', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('import_logs', sa.Column('entity_id', sa.String(), nullable=True))
    op.add_column('import_logs', sa.Column('action', sa.String(), nullable=True))
    op.add_column('import_logs', sa.Column('message', sa.String(), nullable=True))
    op.add_column('import_logs', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('import_logs', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('import_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('import_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_import_logs_is_deleted'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_upload_id'), table_name='import_logs')
    op.create_index(op.f('ix_import_logs_upload_history_id'), 'import_logs', ['upload_history_id'], unique=False)
    op.drop_constraint(op.f('import_logs_upload_id_fkey'), 'import_logs', type_='foreignkey')
    op.create_foreign_key(None, 'import_logs', 'upload_history', ['upload_history_id'], ['id'])
    op.drop_column('import_logs', 'is_deleted')
    op.drop_column('import_logs', 'failed_imports')
    op.drop_column('import_logs', 'imported_by')
    op.drop_column('import_logs', 'upload_id')
    op.drop_column('import_logs', 'imported_at')
    op.drop_column('import_logs', 'total_imported')
    op.add_column('upload_history', sa.Column('upload_type', sa.String(), nullable=True))
    op.add_column('upload_history', sa.Column('success_records', sa.Integer(), nullable=True))
    op.add_column('upload_history', sa.Column('processing_time', sa.Integer(), nullable=True))
    op.add_column('upload_history', sa.Column('status', sa.String(), nullable=True))
    op.add_column('upload_history', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('upload_history', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('upload_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('upload_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_upload_history_is_deleted'), table_name='upload_history')
    op.drop_column('upload_history', 'uploaded_at')
    op.drop_column('upload_history', 'module')
    op.drop_column('upload_history', 'upload_status')
    op.drop_column('upload_history', 'successful_records')
    op.drop_column('upload_history', 'is_deleted')
    op.add_column('validation_logs', sa.Column('upload_history_id', sa.UUID(), nullable=False))
    op.add_column('validation_logs', sa.Column('field_name', sa.String(), nullable=True))
    op.add_column('validation_logs', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('validation_logs', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('validation_logs', sa.Column('updated_by', sa.String(), nullable=True))
    op.alter_column('validation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('validation_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_validation_logs_is_deleted'), table_name='validation_logs')
    op.drop_index(op.f('ix_validation_logs_upload_id'), table_name='validation_logs')
    op.create_index(op.f('ix_validation_logs_upload_history_id'), 'validation_logs', ['upload_history_id'], unique=False)
    op.drop_constraint(op.f('validation_logs_upload_id_fkey'), 'validation_logs', type_='foreignkey')
    op.create_foreign_key(None, 'validation_logs', 'upload_history', ['upload_history_id'], ['id'])
    op.drop_column('validation_logs', 'column_name')
    op.drop_column('validation_logs', 'upload_id')
    op.drop_column('validation_logs', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_logs', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('validation_logs', sa.Column('upload_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('validation_logs', sa.Column('column_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'validation_logs', type_='foreignkey')
    op.create_foreign_key(op.f('validation_logs_upload_id_fkey'), 'validation_logs', 'upload_history', ['upload_id'], ['id'])
    op.drop_index(op.f('ix_validation_logs_upload_history_id'), table_name='validation_logs')
    op.create_index(op.f('ix_validation_logs_upload_id'), 'validation_logs', ['upload_id'], unique=False)
    op.create_index(op.f('ix_validation_logs_is_deleted'), 'validation_logs', ['is_deleted'], unique=False)
    op.alter_column('validation_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('validation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('validation_logs', 'updated_by')
    op.drop_column('validation_logs', 'created_by')
    op.drop_column('validation_logs', 'severity')
    op.drop_column('validation_logs', 'field_name')
    op.drop_column('validation_logs', 'upload_history_id')
    op.add_column('upload_history', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('successful_records', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('upload_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('module', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('upload_history', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_upload_history_is_deleted'), 'upload_history', ['is_deleted'], unique=False)
    op.alter_column('upload_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('upload_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('upload_history', 'updated_by')
    op.drop_column('upload_history', 'created_by')
    op.drop_column('upload_history', 'status')
    op.drop_column('upload_history', 'processing_time')
    op.drop_column('upload_history', 'success_records')
    op.drop_column('upload_history', 'upload_type')
    op.add_column('import_logs', sa.Column('total_imported', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('import_logs', sa.Column('imported_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('import_logs', sa.Column('upload_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('import_logs', sa.Column('imported_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('import_logs', sa.Column('failed_imports', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('import_logs', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'import_logs', type_='foreignkey')
    op.create_foreign_key(op.f('import_logs_upload_id_fkey'), 'import_logs', 'upload_history', ['upload_id'], ['id'])
    op.drop_index(op.f('ix_import_logs_upload_history_id'), table_name='import_logs')
    op.create_index(op.f('ix_import_logs_upload_id'), 'import_logs', ['upload_id'], unique=False)
    op.create_index(op.f('ix_import_logs_is_deleted'), 'import_logs', ['is_deleted'], unique=False)
    op.alter_column('import_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('import_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('import_logs', 'updated_by')
    op.drop_column('import_logs', 'created_by')
    op.drop_column('import_logs', 'message')
    op.drop_column('import_logs', 'action')
    op.drop_column('import_logs', 'entity_id')
    op.drop_column('import_logs', 'entity_type')
    op.drop_column('import_logs', 'upload_history_id')
    op.add_column('employee_master', sa.Column('salary_account', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('micr_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('bank_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('swift_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('salary_payment_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('uan_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('primary_bank_flag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('secondary_bank_flag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('pan_linked_account', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('cost_center', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('bank_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('emergency_contact_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('pf_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('salary_hike_percent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('upi_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('salary_credit_account_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('payroll_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('salary_credit_bank', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('project_allocation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('vendor_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('emergency_contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('ctc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('emergency_contact_relation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('salary_credit_ifsc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('salary_transfer_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('salary_account_verified', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('aadhaar_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('net_salary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('kyc_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('employee_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('pan_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('salary_cycle', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('gross_salary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('esic_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('branch_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('client_allocation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('bank_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employee_master', sa.Column('bank_verification_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employee_master_employee_id'), table_name='employee_master')
    op.create_index(op.f('ix_employee_master_employee_id'), 'employee_master', ['employee_id'], unique=False)
    op.alter_column('employee_master', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('employee_master', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('employee_master', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('employee_master', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('employee_master', 'updated_by')
    op.drop_column('employee_master', 'created_by')
    op.drop_column('employee_master', 'aadhaar')
    op.drop_column('employee_master', 'pan')
    op.drop_column('employee_master', 'hike_percentage')
    op.drop_index(op.f('ix_client_master_client_id'), table_name='client_master')
    op.create_index(op.f('ix_client_master_client_id'), 'client_master', ['client_id'], unique=False)
    op.alter_column('client_master', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('client_master', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('client_master', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('client_master', 'client_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('client_master', 'updated_by')
    op.drop_column('client_master', 'created_by')
    # ### end Alembic commands ###
