"""add_person_id_to_users

Revision ID: cc14e2333eca
Revises: 0002
Create Date: 2026-08-06 16:47:53.728684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc14e2333eca'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'account_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'savings'::character varying"))
    op.drop_constraint(op.f('accounts_business_id_fkey'), 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'business_id')
    op.drop_constraint(op.f('documents_business_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'business_id')
    op.add_column('general_info', sa.Column('person_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_general_info_person_id'), 'general_info', ['person_id'], unique=False)
    op.create_foreign_key(None, 'general_info', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    op.drop_column('leadership_info', 'cfo_additional_info')
    op.drop_column('leadership_info', 'hr_name')
    op.drop_column('leadership_info', 'cfo_email')
    op.drop_column('leadership_info', 'hr_additional_info')
    op.drop_column('leadership_info', 'cfo_name')
    op.drop_column('leadership_info', 'hr_email')
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('transactions', 'classification',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'expense'::character varying"))
    op.add_column('users', sa.Column('person_id', sa.UUID(), nullable=True))
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_firebase_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['person_id'])
    op.drop_constraint(op.f('users_invited_by_user_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'general_info', ['business_id'], ['id'])
    op.drop_column('users', 'invited_by_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_invited_by_user_id_fkey'), 'users', 'users', ['invited_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_firebase_id_key'), 'users', ['firebase_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('users', 'person_id')
    op.alter_column('transactions', 'classification',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'expense'::character varying"))
    op.alter_column('sessions', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('leadership_info', sa.Column('hr_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leadership_info', sa.Column('cfo_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leadership_info', sa.Column('hr_additional_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leadership_info', sa.Column('cfo_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leadership_info', sa.Column('hr_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leadership_info', sa.Column('cfo_additional_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'general_info', type_='foreignkey')
    op.drop_index(op.f('ix_general_info_person_id'), table_name='general_info')
    op.drop_column('general_info', 'person_id')
    op.add_column('documents', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_business_id_fkey'), 'documents', 'general_info', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('accounts', sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('accounts_business_id_fkey'), 'accounts', 'general_info', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('accounts', 'account_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'savings'::character varying"))
    # ### end Alembic commands ###
